name: ipproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2  # Add this line for launcher icons
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter configuration section
flutter:
  uses-material-design: true

  assets:
    - assets/

# flutter_launcher_icons configuration section
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"